-- =============================================================================================
-- Unified Service Scheduler — initial schema.
--
-- HAND-WRITTEN, not generated by `prisma migrate dev`. The load-bearing objects in this file
-- (btree_gist, the generated `during` column, the two partial EXCLUDE constraints, the partial
-- unique and partial scan indexes) are all beyond Prisma's declarative surface — db §5.8.
--
-- Read `docs/database-design.md` §3 alongside this file: the DDL below is that DDL.
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------------------------

-- The entire no-double-booking guarantee rests on this extension: it is what lets a GiST index
-- combine an equality operator (technician_id WITH =) with a range-overlap operator
-- (during WITH &&) in one EXCLUDE constraint. Without btree_gist, GiST cannot index the plain
-- uuid equality half and the constraint cannot be created at all. (ADR-001)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ---------------------------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------------------------

-- No PENDING state: a row is CONFIRMED the instant it is written, because availability is
-- decided synchronously at write time by the exclusion constraint (§3.1).
CREATE TYPE "appointment_status" AS ENUM ('CONFIRMED', 'CANCELLED');

CREATE TYPE "outbox_status" AS ENUM ('PENDING', 'SENT', 'FAILED');

-- ---------------------------------------------------------------------------------------------
-- Reference tables
-- ---------------------------------------------------------------------------------------------

CREATE TABLE "dealerships" (
    "id"            UUID PRIMARY KEY DEFAULT uuidv7(),
    "name"          VARCHAR(255) NOT NULL,
    -- IANA zone; interprets opening_hours and presents UTC instants locally (db §2.1).
    "timezone"      VARCHAR(64)  NOT NULL,
    -- {"mon":[["08:00","18:00"]], "sat":[["08:00","12:00"]], "sun":[]}
    -- List-of-ranges per weekday so split shifts / lunch closes are representable.
    "opening_hours" JSONB        NOT NULL,
    "created_at"    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    "updated_at"    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "customers" (
    "id"            UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id" UUID         NOT NULL REFERENCES "dealerships"("id"),
    "name"          VARCHAR(255) NOT NULL,
    "email"         VARCHAR(255) NOT NULL,
    "phone"         VARCHAR(20),
    "created_at"    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    "updated_at"    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "vehicles" (
    "id"            UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id" UUID        NOT NULL REFERENCES "dealerships"("id"),
    "vin"           VARCHAR(17) NOT NULL,
    "make"          VARCHAR(64) NOT NULL,
    "model"         VARCHAR(64) NOT NULL,
    "year"          SMALLINT    NOT NULL,
    "customer_id"   UUID        NOT NULL REFERENCES "customers"("id"),
    "created_at"    TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "service_types" (
    "id"               UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id"    UUID         NOT NULL REFERENCES "dealerships"("id"),
    "name"             VARCHAR(128) NOT NULL,
    "duration_minutes" INTEGER      NOT NULL,
    "required_skills"  TEXT[]       NOT NULL DEFAULT '{}',
    "created_at"       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    "updated_at"       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- A zero or negative duration would make end_time = start_time and trip
    -- appointments_time_valid on *every* booking of that service — forbid it at the source
    -- rather than discovering it one failed booking at a time (db §2.4).
    CONSTRAINT "service_types_duration_positive" CHECK ("duration_minutes" > 0)
);

CREATE TABLE "technicians" (
    "id"            UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id" UUID         NOT NULL REFERENCES "dealerships"("id"),
    "name"          VARCHAR(255) NOT NULL,
    "skills"        TEXT[]       NOT NULL DEFAULT '{}',
    -- Same JSONB shape as dealerships.opening_hours; a window must fit inside *both*.
    "working_hours" JSONB        NOT NULL,
    -- Soft switch, not a delete: historical appointments must keep their technician reference.
    "is_active"     BOOLEAN      NOT NULL DEFAULT true,
    "created_at"    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    "updated_at"    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE "service_bays" (
    "id"            UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id" UUID        NOT NULL REFERENCES "dealerships"("id"),
    "name"          VARCHAR(64) NOT NULL,
    "is_active"     BOOLEAN     NOT NULL DEFAULT true,
    "created_at"    TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------------------------
-- appointments — the transactional core
-- ---------------------------------------------------------------------------------------------

CREATE TABLE "appointments" (
    "id"              UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id"   UUID NOT NULL REFERENCES "dealerships"("id"),
    "customer_id"     UUID NOT NULL REFERENCES "customers"("id"),
    "vehicle_id"      UUID NOT NULL REFERENCES "vehicles"("id"),
    "service_type_id" UUID NOT NULL REFERENCES "service_types"("id"),
    "technician_id"   UUID NOT NULL REFERENCES "technicians"("id"),
    "service_bay_id"  UUID NOT NULL REFERENCES "service_bays"("id"),

    "start_time"      TIMESTAMPTZ NOT NULL,
    "end_time"        TIMESTAMPTZ NOT NULL,

    -- Derived once, in the database, so start_time/end_time stay the human-readable source of
    -- truth while the constraints get a single indexed expression that cannot drift from them.
    -- '[)' is half-open: an appointment ending at 10:00 does NOT conflict with one starting at
    -- 10:00, so back-to-back bookings are legal (db §5.1).
    "during"          TSTZRANGE GENERATED ALWAYS AS (tstzrange("start_time", "end_time", '[)')) STORED,

    "status"           "appointment_status" NOT NULL DEFAULT 'CONFIRMED',
    "idempotency_key"  VARCHAR(255),
    "request_hash"     CHAR(64),
    "cancelled_at"     TIMESTAMPTZ,
    "cancel_reason"    TEXT,
    "reminder_sent_at" TIMESTAMPTZ,
    "created_at"       TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at"       TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- The DB guarantees the window is non-empty. It does NOT tie end_time to the joined
    -- service_type.duration_minutes — that stays an app-enforced invariant with a single
    -- writer, documented rather than triggered (db §5.9, R-3).
    CONSTRAINT "appointments_time_valid" CHECK ("end_time" > "start_time")
);

-- =============================================================================================
-- THE INVARIANT (ADR-001, §6.1)
--
-- These two constraints are the entire reason this system is built on PostgreSQL. They make an
-- overlapping confirmed booking *impossible to persist* — evaluated atomically at write time
-- under the row lock the INSERT takes, regardless of how many app instances race.
--
-- Application code never decides this. The candidate SELECT in findCandidates() is advisory
-- only; correctness lives here (§6.2).
--
-- WHERE (status = 'CONFIRMED') makes both constraints PARTIAL, which is what lets a cancelled
-- row stop occupying its slot the instant it commits (db §5.3) — no delete required.
-- =============================================================================================

ALTER TABLE "appointments"
    ADD CONSTRAINT "no_technician_overlap"
    EXCLUDE USING gist ("technician_id" WITH =, "during" WITH &&)
    WHERE ("status" = 'CONFIRMED');

ALTER TABLE "appointments"
    ADD CONSTRAINT "no_bay_overlap"
    EXCLUDE USING gist ("service_bay_id" WITH =, "during" WITH &&)
    WHERE ("status" = 'CONFIRMED');

-- Durable idempotency backstop (§6.3). Tenant-scoped on purpose: a global key would let two
-- dealerships that happen to pick the same key collide, and the loser could read the *other
-- tenant's* appointment. Partial on NOT NULL so keyless rows never collide.
CREATE UNIQUE INDEX "appointments_idempotency_key_uniq"
    ON "appointments" ("dealership_id", "idempotency_key")
    WHERE "idempotency_key" IS NOT NULL;

-- ---------------------------------------------------------------------------------------------
-- outbox — reliable event publishing (ADR-006)
-- ---------------------------------------------------------------------------------------------

CREATE TABLE "outbox" (
    -- Doubles as the event_id consumers dedupe on, which is what makes at-least-once delivery
    -- safe (db §2.8).
    "id"             UUID PRIMARY KEY DEFAULT uuidv7(),
    "dealership_id"  UUID        NOT NULL,
    "aggregate_type" VARCHAR(64) NOT NULL,
    "aggregate_id"   UUID        NOT NULL,
    "event_type"     VARCHAR(64) NOT NULL,
    "payload"        JSONB       NOT NULL,
    "status"         "outbox_status" NOT NULL DEFAULT 'PENDING',
    -- Counts real publish FAILURES, never claims. Leasing a row must not touch it, or a healthy
    -- but slowly-published row would drift to the FAILED cap with nothing wrong (db §2.8).
    "attempts"       SMALLINT    NOT NULL DEFAULT 0,
    -- Next eligible time. The relay's claim leases the row by pushing this forward.
    "available_at"   TIMESTAMPTZ NOT NULL DEFAULT now(),
    "published_at"   TIMESTAMPTZ,
    -- Deliberately no updated_at: an append-and-purge operational log, not audited business
    -- data, so the blanket convention does not apply here (db §2.8).
    "created_at"     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------------------------
-- Indexes (§4)
--
-- The two GiST indexes backing the EXCLUDE constraints are created implicitly above and are not
-- repeated here. There is deliberately NO standalone (status) index: a 2-value enum has poor
-- selectivity, and status='CONFIRMED' is already encoded in the partial indexes that matter.
-- ---------------------------------------------------------------------------------------------

-- Tenant-scoped uniqueness. Not global: the same person may be a customer at two independent
-- dealerships, and the same VIN may legitimately appear in two dealerships' records.
CREATE UNIQUE INDEX "customers_dealership_email_uniq" ON "customers" ("dealership_id", "email");
CREATE UNIQUE INDEX "vehicles_dealership_vin_uniq"    ON "vehicles"  ("dealership_id", "vin");

CREATE INDEX "vehicles_customer_idx"      ON "vehicles"      ("customer_id");
CREATE INDEX "technicians_dealership_idx" ON "technicians"   ("dealership_id");
CREATE INDEX "service_bays_dealership_idx" ON "service_bays" ("dealership_id");
CREATE INDEX "service_types_dealership_idx" ON "service_types" ("dealership_id");

-- Backs the qualification check `technicians.skills @> service_types.required_skills`.
CREATE INDEX "technicians_skills_gin_idx" ON "technicians" USING gin ("skills");

CREATE INDEX "appointments_dealership_start_idx" ON "appointments" ("dealership_id", "start_time");
CREATE INDEX "appointments_technician_start_idx" ON "appointments" ("technician_id", "start_time");
CREATE INDEX "appointments_customer_idx"         ON "appointments" ("customer_id");
CREATE INDEX "appointments_vehicle_idx"          ON "appointments" ("vehicle_id");

-- Reminder scan (§5.3). Partial, so the index holds only rows still awaiting a reminder and
-- stays tiny however large the table grows (R-2).
CREATE INDEX "appointments_reminder_due_idx"
    ON "appointments" ("start_time")
    WHERE "status" = 'CONFIRMED' AND "reminder_sent_at" IS NULL;

-- Relay hot path: due, unpublished rows in insertion order. Partial for the same reason.
CREATE INDEX "outbox_due_idx"
    ON "outbox" ("available_at")
    WHERE "status" = 'PENDING';
